### ISSUE TITLE
COPY --from

### ISSUE THREAD

**Issue by lskatz** [ncbi/blast_plus_docs#13]
Hi, could you create instructions on how to import BLAST+ as a layer in my multistage build?  I am copying from this layer in my Dockerfile but something isn't quite right.  Thank you!

Here are the relevant lines from my Dockerfile

    FROM ncbi/blast:2.10.1 AS blast
    COPY --from=blast     /blast                /blast
    ENV PATH="${PATH}:/blast" BLASTDB=/blast/blastdb

I get an error when I try to run `blastn`:

    blastn.REAL: error while loading shared libraries: liblmdb.so.0: cannot open shared object file: No such file or directory

**Comment by tom6931** [comment]
Hi,
   The message indicates that you are missing the LMDB library, which BLAST uses for sequence ID and taxid lookups.  The URL below has a pointer to the library.

 Regards,

Tom


https://www.ncbi.nlm.nih.gov/books/NBK409171/#introduction.Compile_time
