### ISSUE TITLE
Example documentation to download and list database

### ISSUE THREAD

**Issue by phrh** [ncbi/blast_plus_docs#14]
Hello, 

I am following the documentation to download a ncbi database nt.  The files are dowloaded but when I try to  check the available databases in local nothing appears. I try also with the pdbaa database as shown in the example but it does not work. Is there any step missing? 

## Download Protein Data Bank amino acid database (pdbaa)
docker run --rm \
     -v $HOME/blastdb:/blast/blastdb:rw \
     -w /blast/blastdb \
     ncbi/blast \
     update_blastdb.pl pdbaa

## Display database(s) in $HOME/blastdb
docker run --rm \
    -v $HOME/blastdb:/blast/blastdb:ro \
    ncbi/blast \
    blastdbcmd -list /blast/blastdb -remove_redundant_dbs

**Comment by tom6931** [comment]
Hi,
   Thank you for your interest in BLAST+ Docker.  I've just tried this on GCP and it worked (see below).  

   Some questions:
- Are you on a cloud provider?  If so, which one?
- Which OS are you using?
- Did you create a $HOME/blastdb directory?  
- Is there anything in $HOME/blastdb?

Regards,

Tom


`madden@cwl-madden:~$ docker run --rm -v $HOME/blastdb:/blast/blastdb:rw -w /blast/blastdb ncbi/blast update_blastdb.pl pdbaa

madden@cwl-madden:~$ ls blastdb/
pdbaa.pdb  pdbaa.pin  pdbaa.pos  pdbaa.ppd  pdbaa.psq  pdbaa.pto  taxdb.bti
pdbaa.phr  pdbaa.pog  pdbaa.pot  pdbaa.ppi  pdbaa.ptf  taxdb.btd
`

**Comment by phrh** [comment]
Hi,
Thank you for your answer
    Are you on a cloud provider? If so, which one?
No, I am at a local pc
    Which OS are you using?
Description:	Ubuntu 18.04.4 LTS
    Did you create a $HOME/blastdb directory?
I did not, but when I run update_blastdb.pl  It was created.
    Is there anything in $HOME/blastdb?
Yes, the files are there. 
nt.00.tar.gz      nt.03.tar.gz.md5  nt.07.tar.gz      nt.10.tar.gz.md5  nt.14.tar.gz      nt.17.tar.gz.md5  nt.21.tar.gz      nt.24.tar.gz.md5  pdbaa.tar.gz
nt.00.tar.gz.md5  nt.04.tar.gz      nt.07.tar.gz.md5  nt.11.tar.gz      nt.14.tar.gz.md5  nt.18.tar.gz      nt.21.tar.gz.md5  nt.25.tar.gz      pdbaa.tar.gz.md5
nt.01.tar.gz      nt.04.tar.gz.md5  nt.08.tar.gz      nt.11.tar.gz.md5  nt.15.tar.gz      nt.18.tar.gz.md5  nt.22.tar.gz      nt.25.tar.gz.md5
nt.01.tar.gz.md5  nt.05.tar.gz      nt.08.tar.gz.md5  nt.12.tar.gz      nt.15.tar.gz.md5  nt.19.tar.gz      nt.22.tar.gz.md5  nt.26.tar.gz
nt.02.tar.gz      nt.05.tar.gz.md5  nt.09.tar.gz      nt.12.tar.gz.md5  nt.16.tar.gz      nt.19.tar.gz.md5  nt.23.tar.gz      nt.26.tar.gz.md5
nt.02.tar.gz.md5  nt.06.tar.gz      nt.09.tar.gz.md5  nt.13.tar.gz      nt.16.tar.gz.md5  nt.20.tar.gz      nt.23.tar.gz.md5  nt.27.tar.gz
nt.03.tar.gz      nt.06.tar.gz.md5  nt.10.tar.gz      nt.13.tar.gz.md5  nt.17.tar.gz      nt.20.tar.gz.md5  nt.24.tar.gz      nt.27.tar.gz.md5

**Comment by tom6931** [comment]
Thanks for the details. The instructions assume you are on AWS or GCP.
In order to get your files nicely delivered, you should add --decompress to your command-line (see below).  First, you may want to remove the files that are currently present.  Sorry that this is unclear.  I'll make a note to update the documentation.

regards,

Tom

`docker run --rm -v $HOME/blastdb:/blast/blastdb:rw -w /blast/blastdb ncbi/blast update_blastdb.pl pdbaa  --decompress`

**Comment by phrh** [comment]
thank you!
