### ISSUE TITLE
clarify use of megablast, not blastn

### ISSUE THREAD

**Issue by lakras** [ncbi/blast_plus_docs#17]
This is a really excellent guide, and was extremely helpful. I noticed while experimenting with the blast commands that running blastn as shown here takes as much time as after adding `-task megablast`. My understanding (though I could be wrong) is that running blastn by default as described in this guide, `ncbi/blast blastn`, actually runs megablast, and that to run blastn it is necessary to specify `-task blastn`. I think it would be helpful to add a note clarifying that the commands in this document run megablast, not blastn. Thank you so much.

**Comment by christiam** [comment]
Thanks for the feedback @lakras , we have added a clarifying note.
