### ISSUE TITLE
mention blastn output filename limitations (256 characters)

### ISSUE THREAD

**Issue by jvollme** [ncbi/blast_plus_docs#18]
Apaprently outputfilenames for blast are limited to maximum 256 characters. This should be explicitely mentioned (or better: fixed)

**Comment by christiam** [comment]
@jvollme - thanks for the report, we will address the documentation.

**Comment by jvollme** [comment]
Sorry my bad, just realized this is a general Unix/bash restriction. Just didn't come up in my pipeline until a blast-step in a special case. Therefore no need for you to explicitly address this after all...
