### ISSUE TITLE
BLAST Database error: No alias or index file found for protein database with Singularity running

### ISSUE THREAD

**Issue by Hai1983** [ncbi/blast_plus_docs#20]
Dear everyone.

+I try to run Blast with Singularity.
+Firstly, I downloaded the datatbase :
          wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.00.tar.gz
         tar zxvf nr.00.tar.gz
+In this directory: 
         daomhai   394620928 Jan 29 22:01 blast_latest.sif
         daomhai   785474112 Jan 29 21:01 Catfish22a.scaffolds.fa
         daomhai 21758439844 Jan 23 22:41 nr.00.tar.gz
          daomhai    16398992 Jan 23 13:45 taxdb.bti
         daomhai   154795652 Jan 23 13:45 taxdb.btd
         daomhai         545 Jan 21 14:07 nr.pal
         daomhai 39369916416 Jan 21 14:07 nr.pdb
         daomhai 13595021718 Jan 21 12:58 nr.pos
         daomhai   130220032 Jan 21 12:54 nr.ptf
         daomhai  2678679080 Jan 21 12:53 nr.pto
         daomhai  6306876900 Jan 21 12:50 nr.pot
         daomhai    66710822 Jan 21 11:07 nr.00.pin
         daomhai   155170935 Jan 21 08:36 nr.00.phd
         daomhai     3466580 Jan 21 08:36 nr.00.phi
         daomhai    33355348 Jan 21 08:36 nr.00.pog
         daomhai    66710632 Jan 21 08:36 nr.00.ppd
         daomhai      260636 Jan 21 08:36 nr.00.ppi
         daomhai  2009755978 Jan 21 08:36 nr.00.phr
         daomhai  3175349590 Jan 21 08:36 nr.00.psq
+Then, I run blastp:
       /scratch/ulg/bbasv/daomhai/BlastAnalyse/DownloadNR $ singularity run -B 
       /scratch/users/d/a/daomhai/BlastAnalyse/DownloadNR/ /scratch/users/d/a/daomhai/BlastAnalyse/DownloadNR/blast_latest.sif 
        blastp -db /scratch/ulg/bbasv/daomhai/BlastAnalyse/DownloadNR/nr -query 
        /scratch/users/d/a/daomhai/BlastAnalyse/DownloadNR/Catfish22a.scaffolds.fa -out catfish.out
+But I get error:
       BLAST Database error: No alias or index file found for protein database 
        [/scratch/ulg/bbasv/daomhai/BlastAnalyse/DownloadNR/nr] in search path 
         [/home/ulg/bbasv/daomhai:/blast/blastdb:/blast/blastdb_custom:]
+I also make :
        export blastdb='/scratch/users/d/a/daomhai/BlastAnalyse/DownloadNR'
+But it was still a problem.

Please help me to figure out what I am doing wrong ??

Sincerely 
Hai

**Comment by tom6931** [comment]
Hello,
   nr is a mult-volume database, so you need to download all the tar files starting with nr (e.g., nr.01.tar.gz, nr.02.tar.gz).  The BLAST+ packages have a perl script called update_blastdb.pl that will download all the volumes.  If you are looking for a one volume protein database to just try this out, then you may want to try swissprot (swissprot.tar.gz) which has only one volume.
