### ISSUE TITLE
--showall issue

### ISSUE THREAD

**Issue by npsonis** [ncbi/blast_plus_docs#22]
When I execute: ncbi-blast-2.12.0+/bin/update_blastdb.pl --showall --verbose --verbose
I get the following

Net::FTP>>> Net::FTP(3.08_01)
Net::FTP>>>   Exporter(5.72)
Net::FTP>>>   Net::Cmd(3.08_01)
Net::FTP>>>   IO::Socket::SSL(2.044)
Net::FTP>>>     IO::Socket::IP(0.37)
Net::FTP>>>       IO::Socket(1.38)
Net::FTP>>>         IO::Handle(1.36)
Net::FTP=GLOB(0x55ec7173d4f8)<<< 220-
Net::FTP=GLOB(0x55ec7173d4f8)<<<  This warning banner provides privacy and security notices consistent with
Net::FTP=GLOB(0x55ec7173d4f8)<<<  applicable federal laws, directives, and other federal guidance for accessing
Net::FTP=GLOB(0x55ec7173d4f8)<<<  this Government system, which includes all devices/storage media attached to
Net::FTP=GLOB(0x55ec7173d4f8)<<<  this system. This system is provided for Government-authorized use only.
Net::FTP=GLOB(0x55ec7173d4f8)<<<  Unauthorized or improper use of this system is prohibited and may result in
Net::FTP=GLOB(0x55ec7173d4f8)<<<  disciplinary action and/or civil and criminal penalties. At any time, and for
Net::FTP=GLOB(0x55ec7173d4f8)<<<  any lawful Government purpose, the government may monitor, record, and audit
Net::FTP=GLOB(0x55ec7173d4f8)<<<  your system usage and/or intercept, search and seize any communication or data
Net::FTP=GLOB(0x55ec7173d4f8)<<<  transiting or stored on this system. Therefore, you have no reasonable
Net::FTP=GLOB(0x55ec7173d4f8)<<<  expectation of privacy. Any communication or data transiting or stored on this
Net::FTP=GLOB(0x55ec7173d4f8)<<<  system may be disclosed or used for any lawful Government purpose.
Net::FTP=GLOB(0x55ec7173d4f8)<<< 220 FTP Server ready.
Net::FTP=GLOB(0x55ec7173d4f8)>>> USER anonymous
Net::FTP=GLOB(0x55ec7173d4f8)<<< 331 Anonymous login ok, send your complete email address as your password
Net::FTP=GLOB(0x55ec7173d4f8)>>> PASS ....
Net::FTP=GLOB(0x55ec7173d4f8)<<< 230 Anonymous access granted, restrictions apply
Net::FTP=GLOB(0x55ec7173d4f8)>>> CWD /blast/db
Net::FTP=GLOB(0x55ec7173d4f8)<<< 250 CWD command successful
Net::FTP=GLOB(0x55ec7173d4f8)>>> TYPE I
Net::FTP=GLOB(0x55ec7173d4f8)<<< 200 Type set to I
Connected to NCBI
Net::FTP=GLOB(0x55ec7173d4f8)>>> PASV
Net::FTP=GLOB(0x55ec7173d4f8)<<< 227 Entering Passive Mode (130,14,250,10,195,109).
Net::FTP=GLOB(0x55ec7173d4f8)>>> NLST
Net::FTP=GLOB(0x55ec7173d4f8)<<< 421 No transfer timeout (60 seconds): closing control connection
Net::FTP=GLOB(0x55ec7173d4f8)>>> PASV
Net::FTP: Net::Cmd::getline(): unexpected EOF on command channel:  at /home/ncbi-blast-2.12.0+/bin/update_blastdb.pl line 370.
Net::FTP: Net::Cmd::_is_closed(): unexpected EOF on command channel:  at /home/ncbi-blast-2.12.0+/bin/update_blastdb.pl line 337.
Net::FTP: Net::Cmd::_is_closed(): unexpected EOF on command channel:  at /home/ncbi-blast-2.12.0+/bin/update_blastdb.pl line 337.

Any help?

Thanks

**Comment by christiam** [comment]
Hi npsonis, it looks like listing the files on the NCBI FTP site failed. Do you get a different result if you use the command below (notice the addition of the `--passive` option)? Also, please consider using the latest release of BLAST+: version 2.13.0

`update_blastdb.pl --showall --verbose --verbose --passive`

Regards,

Christiam

**Comment by npsonis** [comment]
Hi Christiam,
thanks for the quick reply, it is not often in Github, so I appreciate this.

I updated to 2.13.0. I get the same results, again, either with or without the --passive argument.

Best,

npsonis

**Comment by christiam** [comment]
Hi @npsonis ,

> Could be an issue with my institute firewall?

Yes, that could be an issue. Do you get any errors when you run the command below? 

`curl -sS ftp://ftp.ncbi.nlm.nih.gov/blast/db/ ; echo $?`

Those two commands should output the list of BLAST database archives on the NCBI FTP site and the number 0, e.g.:

```
[...]
-r--r--r--   1 ftp      anonymous       59 Mar 29 16:06 refseq_select_rna.tar.gz.md5
-r--r--r--   1 ftp      anonymous      444 Mar 25 19:38 swissprot-prot-metadata.json
-r--r--r--   1 ftp      anonymous 188181532 Mar 25 19:38 swissprot.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 25 19:38 swissprot.tar.gz.md5
-r--r--r--   1 ftp      anonymous      388 Jun  7  2021 taxdb-metadata.json
-r--r--r--   1 ftp      anonymous 32803593 Mar 28 15:26 taxdb.tar.gz
-r--r--r--   1 ftp      anonymous       47 Mar 28 15:26 taxdb.tar.gz.md5
-r--r--r--   1 ftp      anonymous      629 Mar 29 13:20 tsa_nr-prot-metadata.json
-r--r--r--   1 ftp      anonymous 962085904 Mar 29 13:20 tsa_nr.00.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:20 tsa_nr.00.tar.gz.md5
-r--r--r--   1 ftp      anonymous 738521281 Mar 29 13:20 tsa_nr.01.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:20 tsa_nr.01.tar.gz.md5
-r--r--r--   1 ftp      anonymous 738406196 Mar 29 13:20 tsa_nr.02.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:20 tsa_nr.02.tar.gz.md5
-r--r--r--   1 ftp      anonymous 106782865 Mar 29 13:20 tsa_nr.03.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:20 tsa_nr.03.tar.gz.md5
-r--r--r--   1 ftp      anonymous      634 Mar 29 13:29 tsa_nt-nucl-metadata.json
-r--r--r--   1 ftp      anonymous 1345500474 Mar 29 13:29 tsa_nt.00.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:29 tsa_nt.00.tar.gz.md5
-r--r--r--   1 ftp      anonymous 988161800 Mar 29 13:29 tsa_nt.01.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:29 tsa_nt.01.tar.gz.md5
-r--r--r--   1 ftp      anonymous 810035746 Mar 29 13:29 tsa_nt.02.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:29 tsa_nt.02.tar.gz.md5
-r--r--r--   1 ftp      anonymous 450476043 Mar 29 13:29 tsa_nt.03.tar.gz
-r--r--r--   1 ftp      anonymous       51 Mar 29 13:29 tsa_nt.03.tar.gz.md5
dr-xr-xr-x   2 ftp      anonymous   167936 Jun 30  2020 v4
0
```

**Comment by npsonis** [comment]
Hi,
Yes I get a problem:
/ftp.ncbi.nlm.nih.gov/blast/db/ ; echo $
curl: (7) Failed to connect to ftp.ncbi.nlm.nih.gov port 21 after 3419 ms: Connection refused

**Comment by christiam** [comment]
Hi @npsonis ,
      This may be a firewall issue, per the [curl documentation](https://everything.curl.dev/usingcurl/returns), exit code 7 means:
     

> Failed to connect to host. curl managed to get an IP address to the machine and it tried to setup a TCP connection to the host but failed. This can be because you have specified the wrong port number, entered the wrong host name, the wrong protocol or perhaps because there is a firewall or another network equipment in between that blocks the traffic from getting through.
