### ISSUE TITLE
blastp having issues aligning sequences with low complexity regions

### ISSUE THREAD

**Issue by nthosar9846** [ncbi/blast_plus_docs#23]
I blasted two protein sequences of simillar lengths (1902 aa and 1901aa) which looked pretty similar. We tried to used -softmask options too but blast didn't give any significant results and matched only 29 amino acids.
`blastp -soft_masking false -query orf0324_prot.fasta -subject h37rv_pgrs54_prot.fasta > blastp_orf0324_pgrs54.out`
```
Score = 24.6 bits (52),  Expect = 0.14, Method: Compositional matrix adjust.
 Identities = 29/29 (100%), Positives = 29/29 (100%), Gaps = 0/29 (0%)
```
The nucleotide sequences of these proteins had an identity of 85.20% using blastn. 

I tried to align those sequences again using the global aligner needle and got an alignment with an identity of 79.9%. 
`needle -asequence orf0324_prot.fasta -bsequence h37rv_pgrs54_prot.fasta -outfile needle_orf0324_54.out`
`Length: 2097
Identity:    1676/2097 (79.9%)
Similarity:  1680/2097 (80.1%)
Gaps:         391/2097 (18.6%)
Score: 8713.0`

Are there some other options in blastp that could be used to get around this issue?

**Comment by nthosar9846** [comment]
I have attached the protein files (h37rv_pgrs54_prot.fasta and orf0324_prot.fasta), and the laignment results from blastp and needle.
[blastp_dust_orf0324_54.out.gz](https://github.com/ncbi/blast_plus_docs/files/8913156/blastp_dust_orf0324_54.out.gz)
[h37rv_pgrs54_prot.fasta.gz](https://github.com/ncbi/blast_plus_docs/files/8913157/h37rv_pgrs54_prot.fasta.gz)
[needle_orf0324_54.out.gz](https://github.com/ncbi/blast_plus_docs/files/8913158/needle_orf0324_54.out.gz)
[orf0324_prot.fasta.gz](https://github.com/ncbi/blast_plus_docs/files/8913159/orf0324_prot.fasta.gz)

**Comment by tom6931** [comment]
Please try the command below.  I've turned off composition-based statistics (CBS), and that gives a pretty good alignment. CBS has some seg filtering on the database sequences, which was preventing you from producing an alignment.  Normally, this helps BLAST avoid producing alignments based only on composition.  In your case, it masked out most of the sequences.  

blastp -query orf0324_prot.fasta -subject h37rv_pgrs54_prot.fasta -out temp.out -comp_based_stats 0

**Comment by nthosar9846** [comment]
That worked. Thank you for helping!
