### ISSUE TITLE
How to use a configuration file

### ISSUE THREAD

**Issue by zyosufzai** [ncbi/blast_plus_docs#25]
How do you use/set up a configuration file for blast+ to indicate the database directory? I want to change the search path from [blast:/blast/blastdb:/blast/blastdb_custom:] to a different directory. I tried creating a config file that named config.ncbirc and says says: 
```
[BLAST]
BLASTDB=db/pdbaa
```
but didnt know if I was meant to export the config file or is there a flag to add to the command line?

**Comment by zyosufzai** [comment]
Yes I tried both but I'm still getting the same error :

`
BLAST Database error: No alias or index file found for protein database [pdbaa] in search path [/home/jupyter/blast-plus::]
`

Here is my initial code:

```
blastp -query proteins.fasta -db pdbaa -out proteins_blastp_1align_2.txt -num_alignments 1
```

my config file says: 

```
[BLAST]
BLASTDB=db/pdbaa
```

**Comment by christiam** [comment]
@zyosufzai - The `BLAST.BLASTDB` setting in the config file should be set to a path, not to the path to a BLAST database. If you'd like to use a config file, I'd recommend you create one in one of the paths mentioned in the [documentation](https://www.ncbi.nlm.nih.gov/books/NBK569858/), i.e.: one of: the current working directory, your HOME directory, a directory specified by the NCBI environment variable, or the standard system directory (“/etc” on Unix-like systems, and given by the environment variable SYSTEMROOT on Windows). I'd also recommend that you specify the absolute path to where your BLASTDB resides, e.g.:

```
[BLAST]
BLASTDB=/home/jupyter/blast-plus/db
```

**Comment by zyosufzai** [comment]
okay so just to clarify I dont need to add a flag to my command like blastp -query proteins.fasta -db pdbaa -out proteins_blastp_1align_2.txt -num_alignments 1 --config path/to/config/file. The blast commands will find my config file themselves?

**Comment by christiam** [comment]
Yes, that's correct. Please read the documented linked below, it contains information about how you can configure the BLAST+ command line applications via a configuration file. https://www.ncbi.nlm.nih.gov/books/NBK569858/#_usrman_Config_BLAST_Configuring_BLAST_vi_
I hope this helps, regards,

Christiam
