### ISSUE TITLE
segfaults in step 3 of section 3

### ISSUE THREAD

**Issue by lakras** [ncbi/blast_plus_docs#7]
Hi! First of all, thank you so much for this tutorial.

Everything works great until I get to step 3 of section 3 (running blastn with nt and the 59 KB or 422 KB input file). I keep getting segfaults:

`/blast/bin/blastn: line 25:     9 Segmentation fault      (core dumped) blastn.REAL "$@"`

I've tried changing the output format and I've tried changing the number of threads to 32, 16, or 1. I've tried Ubuntu 18.04 LTS with 500 GB and Ubuntu 20.04 LTS with 500 GB. I'm using a n1-highmem-32 us-east4c. Do you have any suggestions for what could be going wrong?

Thank you so much!

**Comment by tom6931** [comment]
Hello,
  thank you for reporting this.  I've been able to reproduce your problem by following the instructions on github.  I'm looking at this issue right now.

**Comment by lakras** [comment]
Thank you so much!!!!

**Comment by tom6931** [comment]
Hello,
   I've updated the docker file to fix the issue you reported.  Please let us know if you continue to have problems or have any comments.  Otherwise, we'll consider the issue resolved.
